//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hovedopgave1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public string Navn { get; set; }
        public string Adresse { get; set; }
        public string Bopæl { get; set; }
        public string Nationalitet { get; set; }
        public string SprogKundskab { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public string Uddannelse { get; set; }
        public string Periode { get; set; }
        public string Semester { get; set; }
        public string Specialisering { get; set; }
        public string Overbygning { get; set; }
        public string SemesterProjekt { get; set; }
        public string Praktik { get; set; }
        public string Hovedopgave { get; set; }
        public string OpgaveType { get; set; }
        public string StudieJob { get; set; }
        public bool Transport { get; set; }
        public System.DateTime DatoForOprettelse { get; set; }
    }
}
